import { expect, test } from "bun:test";

import { ROUTES } from "../../src/api/client";

/** Routes added in phase 1b (contract section 2); types.ts must be regenerated after them. */
const PHASE_1B_ROUTES = [
  "/api/v1/overview",
  "/api/v1/tasks/{project}/{task}/views",
  "/api/v1/tasks/{project}/{task}/views/{name}",
  "/api/v1/tasks/{project}/{task}/views/validate",
  "/api/v1/tasks/{project}/{task}/views/query",
  "/api/v1/runs/{run_id}/traces",
  "/api/v1/runs/{run_id}/traces/{example_id}",
  "/api/v1/tasks/{project}/{task}/kind",
];

/** Hub routes added in phase 2 (phase 2 contract section 2) that the UI calls. */
const PHASE_2_ROUTES = [
  "/api/v1/hosts",
  "/api/v1/hosts/{host}/connect",
  "/api/v1/hosts/{host}/disconnect",
  "/api/v1/hosts/{host}/runs",
  "/api/v1/sweeps",
  "/api/v1/sweeps/{project}/{sweep_id}",
  "/api/v1/sweeps/{project}/{sweep_id}/cancel_queued",
  "/api/v1/sweeps/{project}/{sweep_id}/extend",
  "/api/v1/projects/{project}/sweeps",
  "/api/v1/runs/{run_id}/pull",
  "/api/v1/gpus",
  "/api/v1/queue",
];

test("types.ts is generated by openapi-typescript and includes every client route", async () => {
  const text = await Bun.file(new URL("../../src/api/types.ts", import.meta.url)).text();
  expect(text).toContain("This file was auto-generated by openapi-typescript.");
  for (const route of [...PHASE_1B_ROUTES, ...PHASE_2_ROUTES, ...Object.values(ROUTES)]) {
    expect(text).toContain(`"${route}": {`);
  }
});
