import { expect, test } from "bun:test";

import { ROUTES } from "../../src/api/client";

/** Routes added in phase 1b (contract section 2); types.ts must be regenerated after them. */
const PHASE_1B_ROUTES = [
  "/api/v1/overview",
  "/api/v1/tasks/{project}/{task}/views",
  "/api/v1/tasks/{project}/{task}/views/{name}",
  "/api/v1/tasks/{project}/{task}/views/validate",
  "/api/v1/tasks/{project}/{task}/views/query",
  "/api/v1/runs/{run_id}/traces",
  "/api/v1/runs/{run_id}/traces/{example_id}",
  "/api/v1/tasks/{project}/{task}/kind",
];

test("types.ts is generated by openapi-typescript and includes every client route", async () => {
  const text = await Bun.file(new URL("../../src/api/types.ts", import.meta.url)).text();
  expect(text).toContain("This file was auto-generated by openapi-typescript.");
  for (const route of [...PHASE_1B_ROUTES, ...Object.values(ROUTES)]) {
    expect(text).toContain(`"${route}": {`);
  }
});
